#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const INSTAGRAM_URL = 'https://www.instagram.com/phieetle/';
const CONTACT_HREF = 'mailto:sophiecmckenzie28@gmail.com';
const IMAGE_EXT = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.heic', '.avif']);

function isImage(f) {
  return IMAGE_EXT.has(path.extname(f).toLowerCase());
}

// Parses "Title, YYYY[optional trailing dots].ext" or just "Title.ext"
function parseGalleryName(filename) {
  const name = path.parse(filename).name;
  const withYear = name.match(/^(.*),\s*(\d{4})[.\s]*$/);
  if (withYear) return { title: withYear[1].trim(), year: withYear[2] };
  const title = name.replace(/[.\s]+$/, '').trim();
  return title ? { title, year: null } : null;
}

// Parses "IMAGE WITHIN TitleHere1.ext" → "TitleHere" (stripped digits)
function parseWithinTarget(filename) {
  const name = path.parse(filename).name;
  if (!name.startsWith('IMAGE WITHIN ')) return null;
  return name.slice('IMAGE WITHIN '.length).replace(/\d+$/, '').trim();
}

function scanGallery(dirName) {
  const absDir = path.join(ROOT, dirName);
  const files = fs.readdirSync(absDir).filter(isImage).sort();
  const gallery = [];
  const withinFiles = [];

  for (const f of files) {
    if (f.startsWith('IMAGE WITHIN ')) {
      withinFiles.push(f);
    } else {
      const parsed = parseGalleryName(f);
      if (parsed) gallery.push({ file: `${dirName}/${f}`, title: parsed.title, year: parsed.year });
    }
  }

  // Case-insensitive lookup so "PO Box outerspace" matches "PO Box Outerspace"
  const lookup = {};
  for (const item of gallery) lookup[item.title.toLowerCase()] = item.title;

  const withinMap = {};
  for (const f of withinFiles) {
    const target = parseWithinTarget(f);
    if (!target) continue;
    const matched = lookup[target.toLowerCase()];
    if (matched) {
      if (!withinMap[matched]) withinMap[matched] = [];
      withinMap[matched].push(`${dirName}/${f}`);
    }
  }

  return { gallery, withinMap };
}

function scanSketches(dirName) {
  const absDir = path.join(ROOT, dirName);
  return fs.readdirSync(absDir).filter(isImage).sort().map(f => ({ file: `${dirName}/${f}` }));
}

const { gallery: illustrations, withinMap: illustrationWithin } = scanGallery('illustrations');
const { gallery: patterns, withinMap: patternWithin } = scanGallery('surfaceandpattern');
const sketches = scanSketches('sketches');

const output = [
  '// Auto-generated by build.js — run "node build.js" after adding images.',
  `var INSTAGRAM_URL = '${INSTAGRAM_URL}';`,
  `var CONTACT_HREF = '${CONTACT_HREF}';`,
  '',
  `var ILLUSTRATIONS = ${JSON.stringify(illustrations, null, 2)};`,
  '',
  `var ILLUSTRATION_WITHIN = ${JSON.stringify(illustrationWithin, null, 2)};`,
  '',
  `var PATTERNS = ${JSON.stringify(patterns, null, 2)};`,
  '',
  `var PATTERN_WITHIN = ${JSON.stringify(patternWithin, null, 2)};`,
  '',
  `var SKETCHES = ${JSON.stringify(sketches, null, 2)};`,
].join('\n');

fs.writeFileSync(path.join(ROOT, 'gallery-data.js'), output, 'utf8');

console.log('gallery-data.js updated!');
console.log(`  Illustrations : ${illustrations.length}`);
console.log(`  Patterns      : ${patterns.length}`);
console.log(`  Sketches      : ${sketches.length}`);
