// Auto-generated by build.js — run "node build.js" after adding images.
var INSTAGRAM_URL = 'https://www.instagram.com/phieetle/';
var CONTACT_HREF = 'mailto:sophiecmckenzie28@gmail.com';

var ILLUSTRATIONS = [
  {
    "file": "illustrations/Aliens, 2025.PNG",
    "title": "Aliens",
    "year": "2025"
  },
  {
    "file": "illustrations/American Woodcock, 2026.PNG",
    "title": "American Woodcock",
    "year": "2026"
  },
  {
    "file": "illustrations/Bath Time, 2026..png",
    "title": "Bath Time",
    "year": "2026"
  },
  {
    "file": "illustrations/Breakfast Party, 2026..png",
    "title": "Breakfast Party",
    "year": "2026"
  },
  {
    "file": "illustrations/Bug Picnic, 2026..PNG",
    "title": "Bug Picnic",
    "year": "2026"
  },
  {
    "file": "illustrations/Coven Tots, 2025.png",
    "title": "Coven Tots",
    "year": "2025"
  },
  {
    "file": "illustrations/Fisherman, 2026..jpg",
    "title": "Fisherman",
    "year": "2026"
  },
  {
    "file": "illustrations/Invasive Snails Poster, 2026.PNG",
    "title": "Invasive Snails Poster",
    "year": "2026"
  },
  {
    "file": "illustrations/PO Box Outerspace, 2026.PNG",
    "title": "PO Box Outerspace",
    "year": "2026"
  },
  {
    "file": "illustrations/Puppy Love, 2026..png",
    "title": "Puppy Love",
    "year": "2026"
  },
  {
    "file": "illustrations/Skeleton Flowers, 2025.PNG",
    "title": "Skeleton Flowers",
    "year": "2025"
  },
  {
    "file": "illustrations/Snake, 2026.png",
    "title": "Snake",
    "year": "2026"
  },
  {
    "file": "illustrations/Warby Parker, 2026..png",
    "title": "Warby Parker",
    "year": "2026"
  }
];

var ILLUSTRATION_WITHIN = {
  "American Woodcock": [
    "illustrations/IMAGE WITHIN American Woodcock1.jpg",
    "illustrations/IMAGE WITHIN American Woodcock2.PNG"
  ],
  "Bug Picnic": [
    "illustrations/IMAGE WITHIN Bug Picnic1.PNG",
    "illustrations/IMAGE WITHIN Bug Picnic2.PNG",
    "illustrations/IMAGE WITHIN Bug Picnic3.PNG",
    "illustrations/IMAGE WITHIN Bug Picnic4.PNG",
    "illustrations/IMAGE WITHIN Bug Picnic5.PNG"
  ],
  "PO Box Outerspace": [
    "illustrations/IMAGE WITHIN PO Box outerspace.PNG"
  ]
};

var PATTERNS = [
  {
    "file": "surfaceandpattern/Apple Juicy Repeat, 2026..png",
    "title": "Apple Juicy Repeat",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Apple Juicy, 2026..png",
    "title": "Apple Juicy",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Critter Bed Flat, 2026.PNG",
    "title": "Critter Bed Flat",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Critter Bed Mockup, 2026.png",
    "title": "Critter Bed Mockup",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Flower Sheets, 2026..PNG",
    "title": "Flower Sheets",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Pear Lady, 2026.PNG",
    "title": "Pear Lady",
    "year": "2026"
  },
  {
    "file": "surfaceandpattern/Pears Repeat, 2026.PNG",
    "title": "Pears Repeat",
    "year": "2026"
  }
];

var PATTERN_WITHIN = {};

var SKETCHES = [
  {
    "file": "sketches/IMG_0611.PNG"
  },
  {
    "file": "sketches/IMG_0710.PNG"
  },
  {
    "file": "sketches/IMG_0716.PNG"
  },
  {
    "file": "sketches/IMG_0717.PNG"
  },
  {
    "file": "sketches/IMG_9153.heic"
  },
  {
    "file": "sketches/IMG_9154.heic"
  }
];